### ISSUE TITLE
Розробити Search Service

### ISSUE THREAD

**Issue by Brazilianian** [MITIT-DEP22/MititWebsite#4]

**Comment by OleksandrIX** [comment]
@Denis11333 зроби запис логів в каталог logs, який знаходиться на одному рівні з каталогом проекта

**Comment by OleksandrIX** [comment]
![Image](https://github.com/MITIT-DEP22/MititWebsite/assets/93474880/ecd3aaf2-043e-4efe-b026-63b20c451776)

**Comment by Brazilianian** [comment]
@OleksandrIX Зроби будь ласка на це окремий issue (цей можна закрити)
